print("Welcome to The Band Name Generator!\n")
print("Let's start!")
city_name = input("What city did you grow up in?\n")
pet_name = input("What is the name of your first pet?\n")
print("Your band name is " + city_name +  " " + pet_name)
